---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: default
  name: sync-resource
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    component: sync-resource
  name: sync-resource
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: sync-resource
    namespace: default